name = "velqa-backend"
main = "server_v2.py"
compatibility_date = "2024-01-01"
compatibility_flags = ["python_workers"]

[vars]
# Secrets: GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET, AI_API_KEY, SERPER_API_KEY

[[d1_databases]]
binding = "DB"
database_name = "scrapyr-db"
database_id = "c9811430-0f70-4bb6-bd89-354661d84208"

[triggers]
crons = ["0 */6 * * *"]
