name = "velqa-backend"
main = "worker.js"
compatibility_date = "2024-09-23"

[vars]
# Secrets (set via Cloudflare dashboard OR wrangler secret put):
# GITHUB_CLIENT_ID     = Ov23li2oOtJSQKCUwIRr
# GITHUB_CLIENT_SECRET = eab81236a5dc5095baaff6bca50b5fd6b9cc87c8
# GROQ_API_KEY         = gsk_9fng...
# SERPER_API_KEY       = a063f93c...

[[d1_databases]]
binding = "DB"
database_name = "scrapyr-db"
database_id = "c9811430-0f70-4bb6-bd89-354661d84208"
